
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package esb;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-15T14:15:31.319-02:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "servicioPagosESB",
                      portName = "ServicioPagoPort",
                      targetNamespace = "http://esb/",
                      wsdlLocation = "http://localhost:8081/PagosService?wsdl",
                      endpointInterface = "esb.ServicioPago")
                      
public class ServicioPagoPortImpl implements ServicioPago {

    private static final Logger LOG = Logger.getLogger(ServicioPagoPortImpl.class.getName());

    /* (non-Javadoc)
     * @see esb.ServicioPago#realizarPago(java.lang.String  arg0 ,)java.lang.Long  arg1 ,)double  arg2 ,)javax.xml.datatype.XMLGregorianCalendar  arg3 )*
     */
    public java.lang.String realizarPago(java.lang.String arg0,java.lang.Long arg1,double arg2,javax.xml.datatype.XMLGregorianCalendar arg3) { 
        LOG.info("Executing operation realizarPago");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return1736736745";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
