
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cliente.callback;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-15T22:33:47.494-02:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "respuestaDelServidorService",
                      portName = "respuestaDelServidorPort",
                      targetNamespace = "http://callback.cliente/",
                      wsdlLocation = "http://localhost:8080/AsincronismoCliente/services/respuestaDelServidorPort?wsdl",
                      endpointInterface = "cliente.callback.RespuestaDelServidor")
                      
public class RespuestaDelServidorPortImpl implements RespuestaDelServidor {

    private static final Logger LOG = Logger.getLogger(RespuestaDelServidorPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cliente.callback.RespuestaDelServidor#metodoAsincResponse(java.lang.String  arg0 )*
     */
    public void metodoAsincResponse(java.lang.String arg0) { 
        LOG.info("Executing operation metodoAsincResponse");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
