
package cliente.callback;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-15T22:33:47.394-02:00
 * Generated source version: 3.1.4
 * 
 */
public final class RespuestaDelServidor_RespuestaDelServidorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://callback.cliente/", "respuestaDelServidorService");

    private RespuestaDelServidor_RespuestaDelServidorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RespuestaDelServidorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RespuestaDelServidorService ss = new RespuestaDelServidorService(wsdlURL, SERVICE_NAME);
        RespuestaDelServidor port = ss.getRespuestaDelServidorPort();  
        
        {
        System.out.println("Invoking metodoAsincResponse...");
        java.lang.String _metodoAsincResponse_arg0 = "_metodoAsincResponse_arg0-2100659709";
        port.metodoAsincResponse(_metodoAsincResponse_arg0);


        }

        System.exit(0);
    }

}
