package edu.middleware.servicios.pagosya;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T15:11:47.608-02:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "PagosService", 
                  wsdlLocation = "http://localhost:8081/PagosService?wsdl",
                  targetNamespace = "http://servicios.middleware.edu/pagosya") 
public class PagosService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios.middleware.edu/pagosya", "PagosService");
    public final static QName PagosPort = new QName("http://servicios.middleware.edu/pagosya", "PagosPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/PagosService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PagosService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/PagosService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PagosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagosService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PagosService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PagosService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PagosService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ProxyServicePortType
     */
    @WebEndpoint(name = "PagosPort")
    public ProxyServicePortType getPagosPort() {
        return super.getPort(PagosPort, ProxyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyServicePortType
     */
    @WebEndpoint(name = "PagosPort")
    public ProxyServicePortType getPagosPort(WebServiceFeature... features) {
        return super.getPort(PagosPort, ProxyServicePortType.class, features);
    }

}
