
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.middleware.servicios.pagosya;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T12:44:58.201-02:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "PagosService",
                      portName = "PagosPort",
                      targetNamespace = "http://servicios.middleware.edu/pagosya",
                      wsdlLocation = "http://localhost:8081/PagosService?wsdl",
                      endpointInterface = "edu.middleware.servicios.pagosya.ProxyServicePortType")
                      
public class PagosPortImpl implements ProxyServicePortType {

    private static final Logger LOG = Logger.getLogger(PagosPortImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.middleware.servicios.pagosya.ProxyServicePortType#invoke(java.lang.Object  arg0 )*
     */
    public java.lang.Object invoke(java.lang.Object arg0) { 
        LOG.info("Executing operation invoke");
        System.out.println(arg0);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
