package edu.middleware.servicios.pagosya;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T12:44:58.225-02:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://servicios.middleware.edu/pagosya", name = "ProxyServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProxyServicePortType {

    @WebMethod
    @RequestWrapper(localName = "invoke", targetNamespace = "http://servicios.middleware.edu/pagosya", className = "edu.middleware.servicios.pagosya.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://servicios.middleware.edu/pagosya", className = "edu.middleware.servicios.pagosya.InvokeResponse")
    @WebResult(name = "return", targetNamespace = "http://servicios.middleware.edu/pagosya")
    public java.lang.Object invoke(
        @WebParam(name = "arg0", targetNamespace = "http://servicios.middleware.edu/pagosya")
        java.lang.Object arg0
    );
}
