
package cliente.callback.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Sun Nov 15 21:10:42 ART 2015
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "metodoAsincResponse", namespace = "http://callback.cliente/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metodoAsincResponse", namespace = "http://callback.cliente/")

public class MetodoAsincResponse {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

