
package cliente.callback.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Sun Nov 15 21:10:42 ART 2015
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "metodoAsincResponseResponse", namespace = "http://callback.cliente/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metodoAsincResponseResponse", namespace = "http://callback.cliente/")

public class MetodoAsincResponseResponse {


}

