
package middleware.composicion.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Mon Nov 09 18:44:24 ART 2015
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "RecibirOrdenResponse", namespace = "http://composicion.middleware/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecibirOrdenResponse", namespace = "http://composicion.middleware/")

public class RecibirOrdenResponse {


}

