
package middleware.composicion.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Mon Nov 09 18:44:24 ART 2015
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "RecibirOrden", namespace = "http://composicion.middleware/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecibirOrden", namespace = "http://composicion.middleware/", propOrder = {"arg0", "arg1", "arg2"})

public class RecibirOrden {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private java.lang.Long arg1;
    @XmlElement(name = "arg2")
    private java.util.ArrayList<middleware.composicion.LineaOrdenCompra> arg2;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.Long getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.Long newArg1)  {
        this.arg1 = newArg1;
    }

    public java.util.ArrayList<middleware.composicion.LineaOrdenCompra> getArg2() {
        return this.arg2;
    }

    public void setArg2(java.util.ArrayList<middleware.composicion.LineaOrdenCompra> newArg2)  {
        this.arg2 = newArg2;
    }

}

