package amazoniacentral;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T13:06:02.719-02:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "EnvioJMSService", 
                  wsdlLocation = "http://localhost:63081/activemq?wsdl",
                  targetNamespace = "http://amazoniacentral/") 
public class EnvioJMSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://amazoniacentral/", "EnvioJMSService");
    public final static QName EnvioJMSPort = new QName("http://amazoniacentral/", "EnvioJMSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:63081/activemq?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnvioJMSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:63081/activemq?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnvioJMSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnvioJMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnvioJMSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EnvioJMSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EnvioJMSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EnvioJMSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EnvioJMS
     */
    @WebEndpoint(name = "EnvioJMSPort")
    public EnvioJMS getEnvioJMSPort() {
        return super.getPort(EnvioJMSPort, EnvioJMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnvioJMS
     */
    @WebEndpoint(name = "EnvioJMSPort")
    public EnvioJMS getEnvioJMSPort(WebServiceFeature... features) {
        return super.getPort(EnvioJMSPort, EnvioJMS.class, features);
    }

}
