
package amazoniacentral;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T15:03:49.455-02:00
 * Generated source version: 3.1.4
 * 
 */
public final class EnvioJMS_EnvioJMSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://amazoniacentral/", "EnvioJMSService");

    private EnvioJMS_EnvioJMSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EnvioJMSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EnvioJMSService ss = new EnvioJMSService(wsdlURL, SERVICE_NAME);
        EnvioJMS port = ss.getEnvioJMSPort();  
        
        {
        System.out.println("Invoking enviarColaMensaje...");
        long _enviarColaMensaje_arg0 = 1889844382253149465l;
        try {
            long _enviarColaMensaje__return = port.enviarColaMensaje(_enviarColaMensaje_arg0);
            System.out.println("enviarColaMensaje.result=" + _enviarColaMensaje__return);

        } catch (JMSException_Exception e) { 
            System.out.println("Expected exception: JMSException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
