package amazoniacentral;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T15:03:49.610-02:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://amazoniacentral/", name = "EnvioJMS")
@XmlSeeAlso({ObjectFactory.class})
public interface EnvioJMS {

    @WebMethod(operationName = "EnviarColaMensaje")
    @RequestWrapper(localName = "EnviarColaMensaje", targetNamespace = "http://amazoniacentral/", className = "amazoniacentral.EnviarColaMensaje")
    @ResponseWrapper(localName = "EnviarColaMensajeResponse", targetNamespace = "http://amazoniacentral/", className = "amazoniacentral.EnviarColaMensajeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long enviarColaMensaje(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    ) throws JMSException_Exception;
}
