
package amazoniacentral;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T13:06:02.660-02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "JMSException", targetNamespace = "http://amazoniacentral/")
public class JMSException_Exception extends Exception {
    
    private amazoniacentral.JMSException jmsException;

    public JMSException_Exception() {
        super();
    }
    
    public JMSException_Exception(String message) {
        super(message);
    }
    
    public JMSException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public JMSException_Exception(String message, amazoniacentral.JMSException jmsException) {
        super(message);
        this.jmsException = jmsException;
    }

    public JMSException_Exception(String message, amazoniacentral.JMSException jmsException, Throwable cause) {
        super(message, cause);
        this.jmsException = jmsException;
    }

    public amazoniacentral.JMSException getFaultInfo() {
        return this.jmsException;
    }
}
