package amazoniacentral;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-15T16:43:02.800-02:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://amazoniacentral/", name = "StockResponse")
@XmlSeeAlso({ObjectFactory.class})
public interface StockResponse {

    @WebMethod
    @RequestWrapper(localName = "obtenerStockResponse", targetNamespace = "http://amazoniacentral/", className = "amazoniacentral.ObtenerStockResponse")
    @ResponseWrapper(localName = "obtenerStockResponseResponse", targetNamespace = "http://amazoniacentral/", className = "amazoniacentral.ObtenerStockResponseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public amazoniacentral.ConfirmacionResponse obtenerStockResponse(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
