package ws.stock.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-14T13:01:54.548-02:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://impl.stock.ws/", name = "StockServiceApi")
@XmlSeeAlso({ObjectFactory.class})
public interface StockServiceApi {

    @WebMethod(action = "urn:AnularReserva")
    @RequestWrapper(localName = "anularReserva", targetNamespace = "http://impl.stock.ws/", className = "ws.stock.impl.AnularReserva")
    @ResponseWrapper(localName = "anularReservaResponse", targetNamespace = "http://impl.stock.ws/", className = "ws.stock.impl.AnularReservaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ws.stock.impl.AnulacionReservaResponse anularReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod(action = "urn:ReservarProducto")
    @RequestWrapper(localName = "reservarProducto", targetNamespace = "http://impl.stock.ws/", className = "ws.stock.impl.ReservarProducto")
    @ResponseWrapper(localName = "reservarProductoResponse", targetNamespace = "http://impl.stock.ws/", className = "ws.stock.impl.ReservarProductoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ws.stock.impl.ReservaResponse reservarProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        ws.stock.impl.Compras arg0
    );
}
